cate_perpage: 5
lesson_perpage: 10
perpage: 20
gravatar: 60
word: 10
answer: 1
category_name: 50
word_meaning: 8
filter_options:
  - all
  - learned
  - unlearned
user:
  email:
    maximum_length: 255
  password:
    minimum_length: 6
answer_size: 1
duration: 3
